# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'TestFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestFramework

pod 'Masonry','1.1.0'
pod 'TZImagePickerController' #iOS8 and later
pod 'OpenCV-iOS'
end
